# Generated by Django 6.0.4 on 2026-04-28 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_courses_subjects_student_courses_projects_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='courses',
            table='course',
        ),
        migrations.AlterModelTable(
            name='subjects',
            table='subject',
        ),
    ]
