# Generated by Django 6.0.4 on 2026-04-28 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_courses_table_alter_subjects_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='courses',
            table='courses',
        ),
        migrations.AlterModelTable(
            name='projects',
            table='projects',
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
        migrations.AlterModelTable(
            name='subjects',
            table='subjects',
        ),
    ]
