# Generated by Django 6.0.4 on 2026-04-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_requestlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='response_type',
            field=models.TextField(blank=True, default='ok', null=True),
        ),
    ]
