# Generated by Django 6.0.4 on 2026-05-01 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_alter_courses_table_alter_projects_table_and_more"),
        ("tasks", "0005_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestlog",
            name="status_code",
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="students.projects",
            ),
        ),
    ]
