name: Deploy Django
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy on Ubuntu server
        run: sudo -n /home/jawad/deploy-study-hub.sh
